{{ config(materialized='table') }}

SELECT
	TIME,
	COUNT(*) AS COUNT,
	AVG(PRICE_CHANGE) AS AVG_PRICE,
	AVG(PRICE_PERCENT_CHANGE) AS AVG_PERCENT_CHANGE
FROM DATA_SCIENCE.RN7ENA.GAINERS
GROUP BY TIME
ORDER BY TIME

